### ISSUE TITLE
Tests for Users (UI)

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#229]
# CRUD
- [x] #230 Positive CRUD tests for Users via the CLI
- [ ] #231 Positive CRUD tests for Users via the UI
- [ ] #233 Negative CRUD tests for Users via the CLI
- [ ] #232 Negative CRUD tests for Users via the UI
# Workflows
- If a function displays proper output in the view you are on, but that output appears in other portions of the UI, does it show up properly there as well?
- Even if it produces the correct result (here or in another part of the UI), how does it affect rendering of said view(s)?
# Security
- See "'Naughty' inputs" above
- Can a user with restricted access get to pages/content they're not supposed to get to?
  - via navigation in UI?
  - via manual entry of URL 
    - Example: if url is "example.com/admin", and you have a non-admin user, can you access it by manually inputting the URL?
  - Access once a user has had privileges removed
  - Does removing access from a user affect/break outputs s/he previously inputted?  
    - Example: User adds items to a workflow (registers systems, creates users, sets up content definitions).  User has access revoked or user is removed.  What is the result in said workflows?
  - Can you copy the contents of a user's access cookie(s) from one machine to another and get unauthorized access?
# Considerations
- Consider all aspects of the UI for your feature.  Think about using a top-down approach to consider all elements in the UI.  Start at one layer and work your way down into each of the appropriate parts of the feature area
- Consider any multiple paths one might take to get to a given area in your feature.  If there are multiple ways to get there, assure that you have coverage for all of these
- Consider how your feature touches on or may affect other parts of the UI or back-end.  How might a change in your feature show itself in other parts of the UI?
