### ISSUE TITLE
CLI: Write tests for Organizations

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#386]
Please write out the tests for gpg keys as determined by stubs provided by #373
- [ ] #398 test_positive_create_1
- [ ] #423 test_postive_create_3
- [ ] #424 test_postive_create_4
