### ISSUE TITLE
End-to-End testcase failures tracker

### ISSUE THREAD

**Issue by san7ket** [SatelliteQE/robottelo#5376]
- [x] tests.foreman.endtoend.test_api_endtoend.AvailableURLsTestCase.test_positive_get_links
Error:
`AssertionError: Sequences differ: [u'/katello/api/compare', u'/katello/api/files/:id'] != [u'/katello/api/compare', u'/katello/api/file_units/:id']  First differing element 1: /katello/api/files/:id /katello/api/file_units/:id  - [u'/katello/api/compare', u'/katello/api/files/:id'] + [u'/katello/api/compare', u'/katello/api/file_units/:id'] ?                                              +++++  : file_units`

- [x] tests.foreman.endtoend.test_ui_endtoend.EndToEndTestCase.test_positive_end_to_end
- [x]  tests.foreman.endtoend.test_ui_endtoend.EndToEndTestCase.test_positive_puppet_install
Error:
```

self = <tests.foreman.endtoend.test_ui_endtoend.EndToEndTestCase testMethod=test_positive_puppet_install>

    @skip_if_not_set('clients')
    def test_positive_puppet_install(self):
        """Perform puppet end to end smoke tests using RH repos.
    
            :id: 30b0f872-d035-431a-988f-2b3fde620c78
    
            :expectedresults: Client should get configured by puppet-module.
            """
        activation_key_name = gen_string('alpha')
        cv_name = gen_string('alpha')
        env_name = gen_string('alpha')
        org_name = gen_string('alpha')
        product_name = gen_string('alpha')
        puppet_module = 'motd'
        puppet_repository_name = gen_string('alpha')
>       repos = self.sync.create_repos_tree(SAT6_TOOLS_TREE)
E       AttributeError: 'EndToEndTestCase' object has no attribute 'sync'

tests/foreman/endtoend/test_ui_endtoend.py:343: AttributeError
```

**Comment by ntkathole** [comment]
Closing this as PR #5615 merged!!
