### ISSUE TITLE
Compute Resource Coverage CLI

### ISSUE THREAD

**Issue by san7ket** [SatelliteQE/robottelo#6135]
Tracker issue to add coverage to compute resource  (VMware, RHV, OSP, Libvirt). Priority ordered
There is a good api helper function which could help automate this:
https://github.com/SatelliteQE/robottelo/blob/master/robottelo/api/utils.py#L297

**CLI Coverage of End-to-End**
The test stubs are 
- [x] Vmware t4 test (Add test to CLI and automate) https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/ui/test_computeresource_vmware.py#L830

- [x] RHV t4 test https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/cli/test_computeresource_rhev.py#L386

- [ ] OSP test https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/cli/test_computeresource_osp.py#L247

- [ ] Libvirt t4 test Add test to CLI and automate

~**CLI Coverage automate High Prio Bugs**~ **TBD**

**Comment by san7ket** [comment]
RHV and VMware E2E done https://github.com/SatelliteQE/robottelo/pull/6337

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
