### ISSUE TITLE
6.7.z branch

### ISSUE THREAD

**Issue by mirekdlugosz** [SatelliteQE/robottelo#7731]
Issue for tracking 6.7.z branching in Nailgun. Once all items on list below are Done, we can branch off.
I'm skipping some of very old PRs and pyup-bot PRs for brevity.

- [x] #7647 - work in progress, not a blocker
- [x] #7686 - merged
- [ ] #7710 - needs review
- [x] #7717 - not a blocker
- [x] #7719 - merged
- [ ] #7725 - we'll probably merge it soon, next round of review pending
- [x] #7726 - labeled DO NOT MERGE, not a branching blocker
- [x] #7728 - merged
- [x] #7729 - merged
- [x] #7730 - needs review, Travis fix

**Comment by mshriver** [comment]
I would consider 7717 definitely not a blocker.

**Comment by mirekdlugosz** [comment]
Branch created out of 5a3003138fb23923a792b169d3d0ccad4a36ccea . #7710 and #7725 did not make it before cutoff due to lack of reviews. I'll be adding comments in them later.
